import { env } from './env';

export const POSTGRES_HOST = env.POSTGRES_HOST;
export const POSTGRES_PORT = env.POSTGRES_PORT;
export const POSTGRES_USERNAME = env.POSTGRES_USERNAME;
export const POSTGRES_PASSWORD = env.POSTGRES_PASSWORD;
export const POSTGRES_DATABASE = env.POSTGRES_DATABASE;
export const POSTGRES_SYNCHRONIZE = env.POSTGRES_SYNCHRONIZE;
